export type Difficulty = "easy" | "medium" | "hard";

export type Category =
  | "streaming"
  | "music"
  | "fitness"
  | "software"
  | "gaming"
  | "news"
  | "food"
  | "cloud"
  | "productivity"
  | "other";

export interface Service {
  slug: string;
  name: string;
  category: Category;
  monthlyPrice: string;
  steps: string[];
  url: string;
  tip: string;
  difficulty: Difficulty;
}

export const services: Service[] = [
  {
    slug: "netflix",
    name: "Netflix",
    category: "streaming",
    monthlyPrice: "$15.49",
    steps: [
      "Sign in to your Netflix account at netflix.com.",
      "Click your profile icon in the top-right corner, then select 'Account'.",
      "Under 'Membership & Billing', click 'Cancel Membership'.",
      "Click 'Finish Cancellation' to confirm.",
      "Your account will remain active until the end of your current billing period.",
    ],
    url: "https://www.netflix.com",
    tip: "Netflix keeps your viewing history for 10 months after cancellation, so you can pick up where you left off if you resubscribe.",
    difficulty: "easy",
  },
  {
    slug: "spotify",
    name: "Spotify",
    category: "music",
    monthlyPrice: "$11.99",
    steps: [
      "Log in to your Spotify account at spotify.com (cancellation must be done on the website, not the app).",
      "Click your profile name in the top-right and select 'Account'.",
      "Scroll down to 'Your plan' and click 'Change plan'.",
      "Scroll to the bottom and click 'Cancel Premium'.",
      "Confirm by clicking 'Yes, cancel' on the confirmation page.",
      "Your account will revert to the free tier at the end of your billing cycle.",
    ],
    url: "https://www.spotify.com",
    tip: "You cannot cancel Spotify Premium through the mobile app. You must use a web browser to manage your subscription.",
    difficulty: "easy",
  },
  {
    slug: "amazon-prime",
    name: "Amazon Prime",
    category: "streaming",
    monthlyPrice: "$14.99",
    steps: [
      "Go to amazon.com and sign in to your account.",
      "Hover over 'Account & Lists' and click 'Prime Membership'.",
      "Click 'Manage Membership' on the right side, then 'Update, cancel and more'.",
      "Click 'End Membership'.",
      "Amazon will show you what benefits you'll lose. Click 'Continue to Cancel'.",
      "Choose whether to end immediately or at the end of the billing period.",
      "Confirm cancellation.",
    ],
    url: "https://www.amazon.com",
    tip: "If you haven't used any Prime benefits during the current billing period, Amazon may offer you a full refund.",
    difficulty: "medium",
  },
  {
    slug: "disney-plus",
    name: "Disney+",
    category: "streaming",
    monthlyPrice: "$9.99",
    steps: [
      "Open the Disney+ app or visit disneyplus.com and sign in.",
      "Click your profile avatar, then select 'Account'.",
      "Under your subscription, click your subscription name (Disney+ Basic or Premium).",
      "Click 'Cancel Subscription'.",
      "Follow the prompts and confirm cancellation.",
    ],
    url: "https://www.disneyplus.com",
    tip: "If you subscribed through Apple, Google, or Roku, you need to cancel through that platform's subscription management instead.",
    difficulty: "easy",
  },
  {
    slug: "hulu",
    name: "Hulu",
    category: "streaming",
    monthlyPrice: "$9.99",
    steps: [
      "Sign in to your Hulu account at hulu.com.",
      "Click your profile name and go to 'Account'.",
      "Click 'Cancel Your Subscription' at the bottom of the Account page.",
      "Select your reason for cancelling and click 'Continue to Cancel'.",
      "Click 'Cancel Subscription' to confirm.",
    ],
    url: "https://www.hulu.com",
    tip: "Hulu often offers discounted plans when you try to cancel. If you're on the fence, it's worth seeing what deal they offer before finalizing.",
    difficulty: "easy",
  },
  {
    slug: "hbo-max",
    name: "HBO Max",
    category: "streaming",
    monthlyPrice: "$16.99",
    steps: [
      "Sign in to your account at max.com.",
      "Click your profile icon and select 'Settings'.",
      "Select 'Subscription' from the menu.",
      "Click 'Cancel Subscription'.",
      "Follow the prompts and confirm your cancellation.",
    ],
    url: "https://www.max.com",
    tip: "HBO Max (now Max) may offer you a discounted rate if you attempt to cancel. The retention offer sometimes cuts the price in half.",
    difficulty: "easy",
  },
  {
    slug: "apple-tv-plus",
    name: "Apple TV+",
    category: "streaming",
    monthlyPrice: "$9.99",
    steps: [
      "On your iPhone or iPad, go to Settings > [Your Name] > Subscriptions.",
      "Find Apple TV+ in your subscription list and tap it.",
      "Tap 'Cancel Subscription' (or 'Cancel Free Trial').",
      "Confirm the cancellation when prompted.",
    ],
    url: "https://tv.apple.com",
    tip: "On a Mac, you can cancel through System Settings > Apple ID > Media & Purchases > Subscriptions. On Windows, use iTunes.",
    difficulty: "easy",
  },
  {
    slug: "youtube-premium",
    name: "YouTube Premium",
    category: "streaming",
    monthlyPrice: "$13.99",
    steps: [
      "Go to youtube.com/paid_memberships and sign in.",
      "Click 'Manage Membership' next to YouTube Premium.",
      "Click 'Deactivate' or 'Cancel membership'.",
      "Select your reason and click 'Continue'.",
      "Confirm by clicking 'Cancel membership'.",
    ],
    url: "https://www.youtube.com",
    tip: "If you're on a family plan, only the plan manager can cancel. Individual family members can only remove themselves.",
    difficulty: "easy",
  },
  {
    slug: "paramount-plus",
    name: "Paramount+",
    category: "streaming",
    monthlyPrice: "$7.99",
    steps: [
      "Sign in to your Paramount+ account at paramountplus.com.",
      "Click your profile icon and select 'Account'.",
      "Click 'Cancel Subscription' under the Subscription section.",
      "Confirm you want to cancel by following the on-screen prompts.",
      "You'll retain access until the end of your billing period.",
    ],
    url: "https://www.paramountplus.com",
    tip: "If you signed up through a third party like Apple or Amazon, you'll need to cancel through that platform's subscription settings.",
    difficulty: "easy",
  },
  {
    slug: "peacock",
    name: "Peacock",
    category: "streaming",
    monthlyPrice: "$7.99",
    steps: [
      "Go to peacocktv.com and sign in to your account.",
      "Click the gear icon or your profile, then select 'Account'.",
      "Under 'Plan & Payment', click 'Change Plan or Cancel'.",
      "Click 'Cancel Plan'.",
      "Confirm cancellation by clicking 'Cancel Plan' again.",
    ],
    url: "https://www.peacocktv.com",
    tip: "Peacock offers a free tier, so you'll still be able to watch some content after cancelling your paid plan.",
    difficulty: "easy",
  },
  {
    slug: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    category: "software",
    monthlyPrice: "$59.99",
    steps: [
      "Go to account.adobe.com and sign in.",
      "Click 'Plans & Payment' in the left sidebar.",
      "Click 'Manage Plan' next to your Creative Cloud subscription.",
      "Click 'Cancel your plan'.",
      "Follow the on-screen prompts, selecting your reason for cancelling.",
      "Review the early termination fee (if on an annual plan paid monthly) and click 'Continue'.",
      "Confirm cancellation.",
    ],
    url: "https://www.adobe.com",
    tip: "If you're on an annual plan paid monthly, Adobe charges an early termination fee (50% of remaining months). Try calling Adobe support to negotiate a waiver or discounted rate.",
    difficulty: "hard",
  },
  {
    slug: "microsoft-365",
    name: "Microsoft 365",
    category: "software",
    monthlyPrice: "$9.99",
    steps: [
      "Go to account.microsoft.com and sign in.",
      "Click 'Services & subscriptions' at the top.",
      "Find Microsoft 365 and click 'Manage'.",
      "Click 'Cancel' or 'Turn off recurring billing'.",
      "Follow the prompts and confirm cancellation.",
    ],
    url: "https://www.microsoft.com",
    tip: "After cancelling, you'll still have read-only access to your OneDrive files, but you won't be able to edit documents in the desktop apps.",
    difficulty: "easy",
  },
  {
    slug: "audible",
    name: "Audible",
    category: "streaming",
    monthlyPrice: "$14.95",
    steps: [
      "Go to audible.com and sign in (you cannot cancel via the app).",
      "Click your name at the top, then 'Account Details'.",
      "Under 'Account Details', find and click 'Cancel your membership' (at the bottom of the page).",
      "Audible will show retention offers. Click 'Continue cancelling' if you want to proceed.",
      "Select your reason for cancelling and confirm.",
    ],
    url: "https://www.audible.com",
    tip: "You keep any audiobooks you've purchased forever, even after cancelling. Unused credits are lost, so use them before you cancel.",
    difficulty: "medium",
  },
  {
    slug: "kindle-unlimited",
    name: "Kindle Unlimited",
    category: "streaming",
    monthlyPrice: "$11.99",
    steps: [
      "Go to amazon.com/kindleunlimited and sign in.",
      "Click 'Manage Membership' or go to 'Your Memberships & Subscriptions'.",
      "Find Kindle Unlimited and click 'Cancel Kindle Unlimited'.",
      "Confirm the cancellation when prompted.",
    ],
    url: "https://www.amazon.com/kindleunlimited",
    tip: "Downloaded Kindle Unlimited books will be removed from your device after cancellation. Finish reading any borrowed books before cancelling.",
    difficulty: "easy",
  },
  {
    slug: "peloton",
    name: "Peloton",
    category: "fitness",
    monthlyPrice: "$13.99",
    steps: [
      "Log in to your Peloton account at members.onepeloton.com.",
      "Click your profile icon and select 'Memberships'.",
      "Click 'Cancel Membership' under your active subscription.",
      "Follow the cancellation prompts and confirm.",
      "If you have a Peloton Bike/Tread with a payment plan, the equipment payments will continue separately.",
    ],
    url: "https://www.onepeloton.com",
    tip: "If you have a Peloton hardware device, the monthly All-Access membership is separate from any equipment financing. Cancelling the membership doesn't affect equipment payments.",
    difficulty: "medium",
  },
  {
    slug: "planet-fitness",
    name: "Planet Fitness",
    category: "fitness",
    monthlyPrice: "$15.00",
    steps: [
      "Visit your local Planet Fitness club in person or send a cancellation letter via certified mail.",
      "Bring a valid photo ID to the front desk.",
      "Fill out the cancellation form provided by the staff.",
      "Request a confirmation receipt or copy of the cancellation form.",
      "Note: You cannot cancel Planet Fitness online or by phone in most locations.",
    ],
    url: "https://www.planetfitness.com",
    tip: "Planet Fitness requires in-person cancellation or a certified letter. Plan to visit the specific club where you signed up, as they generally won't process cancellations at other locations.",
    difficulty: "hard",
  },
  {
    slug: "anytime-fitness",
    name: "Anytime Fitness",
    category: "fitness",
    monthlyPrice: "$40.00",
    steps: [
      "Review your membership agreement for the cancellation policy and any notice period required.",
      "Visit your home club in person to request cancellation.",
      "Fill out the cancellation form at the front desk.",
      "Some locations may require 30 days' written notice.",
      "Request written confirmation of your cancellation and keep it for your records.",
    ],
    url: "https://www.anytimefitness.com",
    tip: "Cancellation policies vary by franchise location. Check your original membership agreement for specific terms, as some require 30 days' notice.",
    difficulty: "hard",
  },
  {
    slug: "ny-times",
    name: "NY Times",
    category: "news",
    monthlyPrice: "$17.00",
    steps: [
      "Sign in to your account at nytimes.com.",
      "Go to your Account page and click 'Subscription' in the sidebar.",
      "Click 'Cancel your subscription' at the bottom.",
      "You may be offered a discounted rate to stay. Decline if you want to cancel.",
      "Confirm the cancellation.",
    ],
    url: "https://www.nytimes.com",
    tip: "The NY Times frequently offers steep discounts when you try to cancel. If cost is the issue, you might get a rate as low as $1/week.",
    difficulty: "medium",
  },
  {
    slug: "wall-street-journal",
    name: "Wall Street Journal",
    category: "news",
    monthlyPrice: "$12.99",
    steps: [
      "Call WSJ customer service at 1-800-JOURNAL (1-800-568-7625).",
      "Request to cancel your subscription.",
      "You may be transferred to a retention specialist who will offer a discounted rate.",
      "Confirm that you want to cancel and ask for a confirmation email.",
      "Alternatively, try the live chat option on wsj.com under 'Help & Contact Us'.",
    ],
    url: "https://www.wsj.com",
    tip: "WSJ often requires a phone call to cancel. Be prepared to decline retention offers firmly if you truly want to cancel.",
    difficulty: "hard",
  },
  {
    slug: "hellofresh",
    name: "HelloFresh",
    category: "food",
    monthlyPrice: "$9.99/serving",
    steps: [
      "Log in to your HelloFresh account at hellofresh.com.",
      "Click your name, then select 'Account Settings'.",
      "Scroll to the bottom and click 'Cancel Plan'.",
      "HelloFresh will try to keep you with offers. Click through to continue cancelling.",
      "Confirm your cancellation. Note: You must cancel before the weekly deadline to avoid the next box.",
    ],
    url: "https://www.hellofresh.com",
    tip: "HelloFresh has a weekly ordering deadline. Make sure to cancel before the deadline or you'll be charged for the next delivery. Consider pausing your plan first if you might come back.",
    difficulty: "medium",
  },
  {
    slug: "blue-apron",
    name: "Blue Apron",
    category: "food",
    monthlyPrice: "$9.99/serving",
    steps: [
      "Log in to your account at blueapron.com.",
      "Click 'Account' and then 'Plan & Delivery'.",
      "Click 'Cancel account' at the bottom of the page.",
      "Follow the prompts and confirm your cancellation.",
    ],
    url: "https://www.blueapron.com",
    tip: "You can skip weeks instead of cancelling outright. This pauses deliveries while keeping your account active.",
    difficulty: "easy",
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    category: "software",
    monthlyPrice: "$12.99",
    steps: [
      "Log in to your NordVPN account at my.nordaccount.com.",
      "Go to 'Billing' in the left sidebar.",
      "Find your subscription and click 'Change Plan'.",
      "Click 'Cancel automatic payments' at the bottom.",
      "Confirm the cancellation. You'll still have access until your plan expires.",
    ],
    url: "https://nordvpn.com",
    tip: "NordVPN offers a 30-day money-back guarantee on all plans. If you're within 30 days, contact support for a full refund instead of just cancelling auto-renewal.",
    difficulty: "easy",
  },
  {
    slug: "expressvpn",
    name: "ExpressVPN",
    category: "software",
    monthlyPrice: "$12.95",
    steps: [
      "Sign in to your account at expressvpn.com.",
      "Click 'My Account' and then 'Manage Settings'.",
      "Click 'Turn off automatic renewal'.",
      "Confirm that you want to disable auto-renewal.",
      "Your service will continue until the end of your current plan period.",
    ],
    url: "https://www.expressvpn.com",
    tip: "ExpressVPN has a 30-day money-back guarantee. Contact live chat support within 30 days of purchase for a full refund.",
    difficulty: "easy",
  },
  {
    slug: "mcafee",
    name: "McAfee",
    category: "software",
    monthlyPrice: "$8.33",
    steps: [
      "Sign in to your McAfee account at home.mcafee.com.",
      "Click 'My Account' and then 'Subscriptions'.",
      "Click 'Turn Off Auto-Renewal' next to your subscription.",
      "Confirm the change.",
      "If the option isn't available, contact McAfee support via chat at 1-866-622-3911.",
    ],
    url: "https://www.mcafee.com",
    tip: "McAfee's auto-renewal can be aggressive. After cancelling, check your email for confirmation, and verify the change in your account to make sure it actually went through.",
    difficulty: "medium",
  },
  {
    slug: "norton",
    name: "Norton",
    category: "software",
    monthlyPrice: "$8.33",
    steps: [
      "Sign in to your Norton account at my.norton.com.",
      "Click 'My Subscriptions'.",
      "Find your active subscription and click 'Turn Off Auto-Renewal'.",
      "Confirm the cancellation.",
      "If you can't find the option, call Norton support at 1-844-488-4540.",
    ],
    url: "https://www.norton.com",
    tip: "Norton's auto-renewal prices are often much higher than the introductory rate. Cancelling and resubscribing as a new customer can save you significant money.",
    difficulty: "medium",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    category: "cloud",
    monthlyPrice: "$11.99",
    steps: [
      "Sign in to your Dropbox account at dropbox.com.",
      "Click your profile avatar and select 'Settings'.",
      "Go to the 'Plan' tab.",
      "Click 'Cancel plan' at the bottom.",
      "Follow the prompts, select a reason, and confirm cancellation.",
      "Your account will revert to the free Basic plan (2 GB) at the end of the billing cycle.",
    ],
    url: "https://www.dropbox.com",
    tip: "If your files exceed the 2 GB free limit, Dropbox won't delete them, but you won't be able to add new files or sync until you're under the limit.",
    difficulty: "easy",
  },
  {
    slug: "icloud-plus",
    name: "iCloud+",
    category: "cloud",
    monthlyPrice: "$2.99",
    steps: [
      "On your iPhone or iPad, go to Settings > [Your Name] > Subscriptions.",
      "Tap 'iCloud+' or 'iCloud Storage'.",
      "Tap 'Downgrade Storage Options' or 'Manage Storage Plan'.",
      "Select the free 5 GB plan.",
      "Confirm the downgrade.",
    ],
    url: "https://www.icloud.com",
    tip: "If you exceed the free 5 GB after downgrading, iCloud will stop backing up your device. Download any important files before changing your plan.",
    difficulty: "easy",
  },
  {
    slug: "google-one",
    name: "Google One",
    category: "cloud",
    monthlyPrice: "$2.99",
    steps: [
      "Go to one.google.com and sign in.",
      "Click 'Settings' (gear icon).",
      "Click 'Cancel membership' under the Membership section.",
      "Follow the prompts and confirm cancellation.",
      "Your storage will revert to the free 15 GB at the end of the billing period.",
    ],
    url: "https://one.google.com",
    tip: "Google One storage is shared across Gmail, Drive, and Photos. If you're over 15 GB after downgrading, you won't be able to send or receive email until you free up space.",
    difficulty: "easy",
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    category: "productivity",
    monthlyPrice: "$30.00",
    steps: [
      "Log in to your Grammarly account at grammarly.com.",
      "Click 'Account' in the left sidebar.",
      "Click 'Subscription' and then 'Cancel Subscription'.",
      "Follow the on-screen prompts and confirm.",
      "Your account will revert to the free plan at the end of the billing period.",
    ],
    url: "https://www.grammarly.com",
    tip: "The free version of Grammarly still catches basic grammar and spelling errors. You only lose advanced features like tone, clarity, and plagiarism detection.",
    difficulty: "easy",
  },
  {
    slug: "canva",
    name: "Canva",
    category: "productivity",
    monthlyPrice: "$14.99",
    steps: [
      "Sign in to Canva at canva.com.",
      "Click the gear icon or your account avatar, then select 'Account Settings'.",
      "Click 'Billing & Plans' in the sidebar.",
      "Click 'Cancel subscription' or 'Cancel plan'.",
      "Follow the cancellation steps and confirm.",
    ],
    url: "https://www.canva.com",
    tip: "Canva's free tier is still quite capable. You'll keep access to designs you created, but premium elements in those designs will be watermarked.",
    difficulty: "easy",
  },
  {
    slug: "linkedin-premium",
    name: "LinkedIn Premium",
    category: "productivity",
    monthlyPrice: "$29.99",
    steps: [
      "Sign in to LinkedIn at linkedin.com.",
      "Click your profile photo, then 'Settings & Privacy'.",
      "Click 'Account preferences' and then 'Subscriptions and payments'.",
      "Click 'Manage Premium account'.",
      "Click 'Cancel subscription' and follow the prompts to confirm.",
    ],
    url: "https://www.linkedin.com",
    tip: "LinkedIn Premium frequently offers discounted rates when you cancel. You may be offered 50% off for the next few months.",
    difficulty: "easy",
  },
  {
    slug: "coursera",
    name: "Coursera",
    category: "productivity",
    monthlyPrice: "$49.00",
    steps: [
      "Sign in to your Coursera account at coursera.org.",
      "Click your profile icon and select 'Settings'.",
      "Scroll down to 'Subscriptions' and click 'Manage'.",
      "Click 'Cancel' next to your Coursera Plus subscription.",
      "Confirm the cancellation.",
    ],
    url: "https://www.coursera.org",
    tip: "Coursera offers a 14-day refund window on annual plans. If you're within that period, you can get a full refund by contacting support.",
    difficulty: "easy",
  },
  {
    slug: "duolingo",
    name: "Duolingo",
    category: "productivity",
    monthlyPrice: "$12.99",
    steps: [
      "If you subscribed through the app store, cancel through your device's subscription settings (Apple: Settings > Subscriptions; Google: Play Store > Subscriptions).",
      "If you subscribed on the web, go to duolingo.com and sign in.",
      "Click your profile icon, then 'Settings'.",
      "Go to the 'Subscription' tab and click 'Cancel subscription'.",
      "Confirm the cancellation.",
    ],
    url: "https://www.duolingo.com",
    tip: "The free version of Duolingo still includes all lessons. You only lose features like unlimited hearts, no ads, and offline access.",
    difficulty: "easy",
  },
  {
    slug: "tinder",
    name: "Tinder",
    category: "other",
    monthlyPrice: "$19.99",
    steps: [
      "Open the Tinder app on your phone.",
      "Tap your profile icon, then 'Settings'.",
      "Scroll down and tap 'Manage Payment Account' or go to your device's subscription settings.",
      "For iOS: Settings > Subscriptions > Tinder > Cancel.",
      "For Android: Play Store > Subscriptions > Tinder > Cancel.",
    ],
    url: "https://www.tinder.com",
    tip: "Deleting the Tinder app does not cancel your subscription. You must cancel through your device's subscription settings or you'll continue to be charged.",
    difficulty: "medium",
  },
  {
    slug: "bumble",
    name: "Bumble",
    category: "other",
    monthlyPrice: "$19.99",
    steps: [
      "Open the Bumble app.",
      "Tap your profile icon, then the gear icon for 'Settings'.",
      "If subscribed through app stores, cancel through your device's subscription manager.",
      "For iOS: Settings > [Your Name] > Subscriptions > Bumble > Cancel.",
      "For Android: Google Play Store > Subscriptions > Bumble > Cancel.",
    ],
    url: "https://www.bumble.com",
    tip: "Like Tinder, deleting the Bumble app does not cancel your subscription. Always cancel through your device's subscription settings.",
    difficulty: "medium",
  },
  {
    slug: "xbox-game-pass",
    name: "Xbox Game Pass",
    category: "gaming",
    monthlyPrice: "$17.99",
    steps: [
      "Go to account.microsoft.com/services and sign in with your Microsoft account.",
      "Find 'Xbox Game Pass' in your subscriptions.",
      "Click 'Manage' and then 'Cancel subscription'.",
      "Follow the prompts, choosing whether to cancel immediately or at the end of the billing period.",
      "Confirm the cancellation.",
    ],
    url: "https://www.xbox.com/gamepass",
    tip: "You'll lose access to all Game Pass games when your subscription ends. Any games you purchased at a Game Pass discount will remain in your library.",
    difficulty: "easy",
  },
  {
    slug: "playstation-plus",
    name: "PlayStation Plus",
    category: "gaming",
    monthlyPrice: "$17.99",
    steps: [
      "On your PlayStation console, go to Settings > Account Management > Account Information > PlayStation Subscriptions.",
      "Select 'PlayStation Plus' and click 'Turn Off Auto-Renew'.",
      "Alternatively, go to store.playstation.com, sign in, click your avatar > 'Subscription Management'.",
      "Click 'Turn Off Auto-Renew' next to PS Plus.",
      "Confirm the change.",
    ],
    url: "https://www.playstation.com",
    tip: "You'll lose access to your PS Plus monthly games when the subscription expires, but you'll regain access if you resubscribe later.",
    difficulty: "easy",
  },
  {
    slug: "nintendo-switch-online",
    name: "Nintendo Switch Online",
    category: "gaming",
    monthlyPrice: "$3.99",
    steps: [
      "On your Nintendo Switch, go to the Home menu and select 'Nintendo eShop'.",
      "Click your profile icon in the top-right corner.",
      "Scroll down and select 'Nintendo Switch Online'.",
      "Select 'Turn Off Automatic Renewal'.",
      "Confirm the change.",
    ],
    url: "https://www.nintendo.com",
    tip: "You can also manage your subscription at accounts.nintendo.com under 'Shop Menu' > 'Nintendo Switch Online'.",
    difficulty: "easy",
  },
  {
    slug: "hinge",
    name: "Hinge",
    category: "other",
    monthlyPrice: "$29.99",
    steps: [
      "Hinge subscriptions are managed through your device's app store.",
      "For iOS: Go to Settings > [Your Name] > Subscriptions > Hinge > Cancel Subscription.",
      "For Android: Open Google Play Store > tap your profile > Payments & subscriptions > Subscriptions > Hinge > Cancel.",
      "Confirm the cancellation.",
    ],
    url: "https://www.hinge.co",
    tip: "The free version of Hinge still lets you send likes and match with people. Premium mainly adds filters and unlimited likes.",
    difficulty: "easy",
  },
  {
    slug: "calm",
    name: "Calm",
    category: "other",
    monthlyPrice: "$14.99",
    steps: [
      "If subscribed via app store, cancel through your device's subscription settings.",
      "For iOS: Settings > [Your Name] > Subscriptions > Calm > Cancel.",
      "For Android: Play Store > Subscriptions > Calm > Cancel.",
      "If subscribed on calm.com: Sign in, go to 'Settings' > 'Manage Subscription' > 'Cancel Subscription'.",
      "Confirm cancellation.",
    ],
    url: "https://www.calm.com",
    tip: "Calm offers a lifetime subscription option. If you use it regularly, the lifetime plan may be more cost-effective than the monthly subscription.",
    difficulty: "easy",
  },
  {
    slug: "headspace",
    name: "Headspace",
    category: "other",
    monthlyPrice: "$12.99",
    steps: [
      "If subscribed through an app store, cancel via your device's subscription settings.",
      "For iOS: Settings > [Your Name] > Subscriptions > Headspace > Cancel.",
      "For Android: Play Store > Subscriptions > Headspace > Cancel.",
      "If subscribed at headspace.com: Sign in, click 'Settings' > 'Subscription' > 'Cancel'.",
      "Confirm cancellation.",
    ],
    url: "https://www.headspace.com",
    tip: "Headspace occasionally runs promotions for returning subscribers. After cancelling, wait a few weeks and you might receive a discounted offer to come back.",
    difficulty: "easy",
  },
  {
    slug: "instacart",
    name: "Instacart",
    category: "food",
    monthlyPrice: "$9.99",
    steps: [
      "Open the Instacart app or go to instacart.com and sign in.",
      "Tap the three lines or your profile icon, then 'Account Settings'.",
      "Select 'Instacart+ Membership'.",
      "Tap 'Cancel membership'.",
      "Follow the prompts and confirm cancellation.",
    ],
    url: "https://www.instacart.com",
    tip: "Instacart+ mainly provides free delivery on orders over $35. Calculate whether you order enough to justify the membership cost.",
    difficulty: "easy",
  },
  {
    slug: "doordash-dashpass",
    name: "DoorDash DashPass",
    category: "food",
    monthlyPrice: "$9.99",
    steps: [
      "Open the DoorDash app or go to doordash.com.",
      "Tap your profile icon or the menu icon.",
      "Select 'Manage DashPass'.",
      "Tap 'Cancel membership'.",
      "Follow the prompts and confirm. You'll keep access until the end of your billing period.",
    ],
    url: "https://www.doordash.com",
    tip: "DashPass only saves you money if you order frequently. If you order fewer than 2-3 times per month, the membership likely isn't worth it.",
    difficulty: "easy",
  },
  {
    slug: "uber-one",
    name: "Uber One",
    category: "food",
    monthlyPrice: "$9.99",
    steps: [
      "Open the Uber or Uber Eats app.",
      "Tap your profile icon, then 'Uber One'.",
      "Scroll down and tap 'Manage Membership'.",
      "Tap 'Cancel Membership'.",
      "Confirm by following the on-screen prompts.",
    ],
    url: "https://www.uber.com",
    tip: "Uber One benefits apply to both Uber rides and Uber Eats. Make sure you're not using either service enough to justify the cost before cancelling.",
    difficulty: "easy",
  },
  {
    slug: "walmart-plus",
    name: "Walmart+",
    category: "other",
    monthlyPrice: "$12.95",
    steps: [
      "Go to walmart.com and sign in to your account.",
      "Click your account icon and select 'Walmart+ Account'.",
      "Click 'Manage membership'.",
      "Click 'Cancel Walmart+'.",
      "Select your reason and confirm the cancellation.",
    ],
    url: "https://www.walmart.com",
    tip: "Walmart+ includes free delivery, fuel discounts, and Paramount+ Essential. Make sure you're not using Paramount+ through Walmart+ before cancelling.",
    difficulty: "easy",
  },
  {
    slug: "costco",
    name: "Costco",
    category: "other",
    monthlyPrice: "$6.67",
    steps: [
      "Visit your local Costco warehouse and go to the Membership counter.",
      "Bring your Costco membership card and a valid photo ID.",
      "Request cancellation and a prorated refund of your membership fee.",
      "Costco offers a 100% satisfaction guarantee on memberships, so you can cancel anytime for a full refund.",
    ],
    url: "https://www.costco.com",
    tip: "Costco provides a full refund on membership at any time. You can also cancel by calling 1-800-774-2678 or through the website under Account > Membership > Cancel.",
    difficulty: "easy",
  },
  {
    slug: "sirius-xm",
    name: "Sirius XM",
    category: "other",
    monthlyPrice: "$16.99",
    steps: [
      "Call SiriusXM customer service at 1-866-635-2349.",
      "Tell the representative you want to cancel your subscription.",
      "Be prepared for multiple retention offers and discounted rates.",
      "Firmly confirm you want to cancel if you've decided.",
      "Ask for a confirmation number and email.",
    ],
    url: "https://www.siriusxm.com",
    tip: "SiriusXM is notoriously difficult to cancel and will offer many discounts. If you do want to keep it, this is a good time to negotiate a lower rate. You must call to cancel; there is no online option.",
    difficulty: "hard",
  },
  {
    slug: "strava",
    name: "Strava",
    category: "fitness",
    monthlyPrice: "$11.99",
    steps: [
      "If subscribed via app store, cancel through your device's subscription settings.",
      "If subscribed on strava.com: Sign in and click 'Settings'.",
      "Click 'Subscription' in the sidebar.",
      "Click 'Cancel my plan' and follow the prompts.",
      "Confirm cancellation.",
    ],
    url: "https://www.strava.com",
    tip: "The free version of Strava still tracks your activities and shows them on a map. You lose route planning, training plans, and detailed analytics.",
    difficulty: "easy",
  },
  {
    slug: "crunchyroll",
    name: "Crunchyroll",
    category: "streaming",
    monthlyPrice: "$7.99",
    steps: [
      "Sign in to your Crunchyroll account at crunchyroll.com.",
      "Click your profile avatar and select 'Settings'.",
      "Go to the 'Subscription' tab.",
      "Click 'Cancel Subscription' at the bottom.",
      "Confirm cancellation. You'll retain access until the end of your billing period.",
    ],
    url: "https://www.crunchyroll.com",
    tip: "Crunchyroll has a free tier with ads. You'll still be able to watch many shows after cancelling, just with advertisements and a delay on new episodes.",
    difficulty: "easy",
  },
  {
    slug: "twitch",
    name: "Twitch",
    category: "streaming",
    monthlyPrice: "$8.99",
    steps: [
      "Go to twitch.tv and sign in.",
      "Click your profile icon and select 'Subscriptions'.",
      "Find the channel subscription you want to cancel.",
      "Click the gear icon next to the subscription and select 'Don't Renew Subscription'.",
      "For Twitch Turbo: Go to twitch.tv/turbo and click 'Cancel' in the subscription management area.",
    ],
    url: "https://www.twitch.tv",
    tip: "Twitch channel subscriptions and Twitch Turbo are separate. Make sure you cancel the right one. If you subscribed via Amazon Prime, it won't auto-renew anyway.",
    difficulty: "easy",
  },
];

export const categories: Category[] = [
  "streaming",
  "music",
  "fitness",
  "software",
  "gaming",
  "news",
  "food",
  "cloud",
  "productivity",
  "other",
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: Category): Service[] {
  return services.filter((s) => s.category === category);
}
